### ISSUE TITLE
Bug in getValueForKey

### ISSUE THREAD

**Issue by szhernovoy** [ronp001/SwiftRedis#1]
Hi,
I SET a value 8 for the key "config:test" in my Redis.
When I try to retrieve it using your piece if code:
`redis.getValueForKey("config:test", completionHandler: { (success, key, result, cmd) in
            if success {
                print("the stored data for \(key) is \(result!.stringVal)")`

I receive
`the stored data for config:test is Optional("Optional(8)")`

where the inner Optional can't be unwrapped because it is just a string with content "Optional(8)" that has a length 11 and contains character "8". 

Please look at this

**Comment by ronp001** [comment]
Can you post the code you used to store the value?
