### ISSUE TITLE
Swift 3. Connection error

### ISSUE THREAD

**Issue by szhernovoy** [ronp001/SwiftRedis#3]
Hi,

I am trying to move SwiftRedis to Swift 3 (IOS10, Xcode 8). After fixing compiler errors I am receiving the connection error. The whole log is below. Could you please help to fix it

`input stream: <stream is nil>   output stream: <stream is nil>
connecting...
input stream: .OpenCompleted
sending next command: Optional(RedisCommand(auth))
sendPendingDataIfPossible: not sending data because outputStream.hasSpaceAvaialble is false
sending command string: Optional("*2\r\n$4\r\nAUTH\r\n$16\r\n<PASSWORD IS HERE>\r\n")
input stream: .HasBytesAvaialable
readData: reading up to 1024 from stream
readData: read Optional(5) bytes
read type char: 'Optional("\0")'
RedisInterface: connection error Could not parse response received(unexpected character received while expecting type char: 'Optional("\0")')
read type char: 'Optional("\0")'
RedisInterface: connection error Could not parse response received(unexpected character received while expecting type char: 'Optional("\0")')
read type char: 'Optional("\0")'
RedisInterface: connection error Could not parse response received(unexpected character received while expecting type char: 'Optional("\0")')
read type char: 'Optional("\0")'
RedisInterface: connection error Could not parse response received(unexpected character received while expecting type char: 'Optional("\0")')
read type char: 'Optional("\0")'
RedisInterface: connection error Could not parse response received(unexpected character received while expecting type char: 'Optional("\0")')
`

**Comment by ronp001** [comment]
Hi - I pushed an update that fixes Swift 3 compliance. Can you test with the new version and see if works better?

**Comment by szhernovoy** [comment]
Hi, yes it seems to working. Great, thank you!
