### ISSUE TITLE
Strange behaviour of setDataForKey

### ISSUE THREAD

**Issue by szhernovoy** [ronp001/SwiftRedis#4]
Hi,

there is a strange thing that I can't figure out with. My app records audio from mic and then puts it in Redis for further processing on backend. The code is very simple:

`
            let audioData = try? Data(contentsOf: fileURL)
            let dataSize = audioData?.count
            let redisKey = "wm:\(randomString(10))"

            print("[+] Sending to \(redisKey), size \(dataSize!)")

                redis.setDataForKey(redisKey, data: audioData!, completionHandler: { success, cmd in
                    if success {

                        print("[+] Sent to \(redisKey)")
                    } else {
                        print("File sending error")

                    }
                })
`
When recorded audio duration is less than 10 sec (dataSize < ~135kB) everything works perfectly good. If I set duration to 10+ sec (dataSize > ~135kB) the setDataForKey closure never gets called. No errors or anything in the log. Just nothing happens.

Any ideas?

**Comment by ronp001** [comment]
I think I fixed the problem:  OutputStream does not seem to enjoy sending very large buffers.  The fix is to split it into smaller chunks.  It would be great if you could test the latest version and let me know if it works well for you now.

**Comment by szhernovoy** [comment]
Hi, sorry for not responding promptly, been on vacation. Yes, it looks like this problem is fixed. Thanks!
